PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX brick: <https://brickschema.org/schema/Brick#>
PREFIX bldg: <http://bldg-59#>
SELECT  ?cooling_sig_col ?oat_col ?sat_col ?satsp_col ?rat_col ?oa_dmpr_sig_col ?mat_col# ?heating_sig_col
WHERE {
    ?equip a brick:AHU .
    ?equip brick:hasPart ?cooling_coil, ?oa_dmpr. # ?heating_coil,
    ?equip brick:hasPoint ?oat_col, ?sat_col, ?satsp_col, ?rat_col, ?mat_col.

    ?oat_col rdf:type brick:Outside_Air_Temperature_Sensor .
    ?sat_col rdf:type brick:Supply_Air_Temperature_Sensor .
    ?satsp_col rdf:type brick:Supply_Air_Temperature_Setpoint .
    ?rat_col rdf:type brick:Return_Air_Temperature_Sensor .
    ?mat_col rdf:type brick:Mixed_Air_Temperature_Sensor .

    ?cooling_coil           rdf:type        brick:Cooling_Coil .
    ?cooling_coil           brick:hasPoint  ?cooling_sig_col .
    ?cooling_sig_col        rdf:type        brick:Valve_Position_Command .

    ?oa_dmpr                rdf:type        brick:Outside_Damper .
    ?oa_dmpr                brick:hasPoint  ?oa_dmpr_sig_col .
    ?oa_dmpr_sig_col        rdf:type        brick:Damper_Position_Command .

    #    ?heating_coil           rdf:type        brick:Heating_Coil .
    #    ?heating_coil           brick:hasPoint  ?heating_sig_col .
    #    ?heating_sig_col        rdf:type        brick:Valve_Position_Command .

}