PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX brick: <https://brickschema.org/schema/Brick#>
PREFIX bldg: <http://bldg-59#>
SELECT  ?oa_dmpr_sig_col
WHERE {
    ?equip a brick:AHU .
    ?equip brick:hasPart ?oa_dmpr. # ?heating_coil,

    ?oa_dmpr                rdf:type        brick:Outside_Damper .
    ?oa_dmpr                brick:hasPoint  ?oa_dmpr_sig_col .
    ?oa_dmpr_sig_col        rdf:type        brick:Damper_Position_Command .
}
