name: Deploy docs to gh-pages

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "docs/**"
  workflow_dispatch:


# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      # Install dependencies
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: "Install Poetry"
        run: python -m pip install poetry && python -m poetry install --with docs
      - name: "Build the book"
        run: jupyter-book build .
      - name: "GitHub Pages action"
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "_build/html"