name: Deploy docs to gh-pages

on:
  #   Trigger the workflow on push to main branch
  #  push:
  #    branches:
  #      - main
  #      - dev
  workflow_dispatch:


# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      # Install dependencies
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: "Install Poetry"
        run: python -m pip install poetry;
      - name: "Install dependencies and build book"
        run: python -m poetry install --with docs
      - name: "Build the book"
        run: jupyter-book build docs
      - name: "GitHub Pages action"
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html